### ISSUE TITLE
Feathers v5 launch checklist

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#2905]
## Website

- [x] Move [dove.feathersjs.com](https://dove.feathersjs.com/) to [feathersjs.com](https://feathersjs.com/)
- [x] Add redirects in docs.feathersjs.com to feathersjs.com
- [x] Review redirects in docs.feathersjs.com
- [x] Fix Algolia search
- [x] Update Google Analytics
- [ ] Add awesome ecosystem auto deployments

## Guides

- [x] Verify quick start and add to feathers-chat
- [x] Stackblitz or ReplIt Quick Start (and chat) runners
- [x] Ensure guide content is up to date with CLI generated code
- [x] Ensure https://github.com/feathersjs/feathers-chat examples reflect the current guide
- [x] CLI guide
- [x] Review migration guide

## Docs

- [x] Review all Database adapter documentation
- [x] Update API overview image
- [x] Querying associations
- [ ] Many-to-many (?)
- [ ] Security page

## Functionality

- [x] Fix handling of `filterQuery` and adapter commons
- [x] Allow support for patch schemas

## Publishing

- [ ] Publish 5.0.0 final

## Ecosystem

- [x] feathers-hooks-common
- [x] feathers-sequelize
- [ ] feathers-mongoose
- [ ] feathers-authentication-management
- [ ] feathers-permissions
- [ ] feathers-batch
- [x] feathers-sync
- [ ] feathers-swagger
- [ ] feathers-mailer
- [ ] feathers-blob (?)
- [x] Deprecate feathers-authentication-hooks
- [ ] Deprecate feathers-nedb
- [ ] Deprecate feathers-mongodb (moved to `@feathersjs/mongodb`)
- [ ] Deprecate feathers-knex (moved to `@feathersjs/knex`)
- [ ] Deprecate feathers-memory (moved to `@feathersjs/memory`)

**Comment by fratzinger** [comment]
Packages I got covered:
- feathers-hooks-common
- feathers-sequelize
- feathers-authentication-management

I've also added `setField` from `feathers-authentication-hooks` to `feathers-hooks-common` (see https://hooks-common.feathersjs.com/hooks.html#setfield). It is the only hook there. So imo we could deprecate feathers-authentication-hooks.

**Comment by daffl** [comment]
Amazing! Thanks for being on that. Is the `setField` hook out already and compatible with v4? In that case I could deprecate it right now.

**Comment by fratzinger** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/22286818/205573421-7ced4024-fe92-4b59-94e2-8e099792fce0.png">

yes, it is 😊

**Comment by jdkdev** [comment]
@daffl 

If there is a point where someone is needed to review writing  / follow a guide to make sure it works.  Please let me know the task and a desired due date.

I'd like to earn a "feather of honor" somehow with Dove.

**Comment by fratzinger** [comment]
I've created a typescript version of `feathers-mailer` (see https://github.com/feathersjs-ecosystem/feathers-mailer/pull/33). feathers-mailer really has no crow/dove-specific code but this version follows the ts refactoring of all packages.
