### ISSUE TITLE
Feathers Buzzard Release

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#436]
# Feathers Buzzard

This is the release issue to keep track of all the moving parts across all the repos. This is the release issue to keep track of all the moving parts across all the repos. Expected official release date Q1 2017.

The main goal of this release is to bring Feathers core to v3, improve our operations side of things to make managing Github easier, fix a few things with hooks and events that will be breaking changes, and make sure we are engine agnostic.

![buzzard5](https://cloud.githubusercontent.com/assets/599019/19430535/c872c0b2-9411-11e6-87d0-b77512b3c87d.jpg)
_the Buzzard going in for the kill_
## Core and Core Modules
- [x] [Add code coverage to all repos](https://github.com/feathersjs/feathers/issues/431)
- [x] [Move to all repos to ESlint semistandard](https://github.com/feathersjs/feathers/issues/432)
- [x] [Add automatic changelog generation to all repos](https://github.com/feathersjs/feathers/issues/433)
- [x] [Add `.github` folder to all repos for issue and PR templates](https://github.com/feathersjs/feathers/issues/435)
- [ ] [Make hooks part of core](https://github.com/feathersjs/feathers/issues/408)
- [ ] Make emitting service events a hook #408, #376  _ie. not by default_
- [ ] Event filters should get all connections  #388, #421 _related to above_
- [ ] Hooks coerce from querystring to data types when appropriate
- [ ] [Drop support for `feathers-configuration` in it's current form](https://github.com/feathersjs/feathers-configuration/issues/25)
- [x] Drop support for Node v0.10, v0.12, and iojs
- [ ] [Add Github bot for managing issues and PRs](https://github.com/feathersjs/feathers/issues/387)
## Authentication
- [ ] [Official refresh token support](https://github.com/feathersjs/feathers-authentication/issues/22)

## Service Adapters
- [ ] Supporting special `$search` param on database adapters (https://github.com/feathersjs/feathers/issues/334)
- [ ] [Feathers Twilio 1.0](https://github.com/feathersjs/feathers-twilio/milestones/1.0)
- [ ] [Feathers Mailer 1.1](https://github.com/feathersjs/feathers-mailer/milestones/1.1)
- [ ] [Feathers Blob 1.3](https://github.com/feathersjs/feathers-blob/milestones/1.3)
- [ ] Feather Redis (proposed)
- [ ] Feathers PouchDB (proposed) - may also give us offline sync for client for free.
## Documentation

TBD after new docs are released.

**Comment by Download** [comment]
### Core and Core Modules
* [ ] Enable [unregistering of services and hooks](https://github.com/feathersjs/feathers/issues/446)
